# Generated by Django 3.0.2 on 2020-01-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='race',
            field=models.CharField(choices=[('M', 'Pies'), ('F', 'Suczka'), ('X', 'Nieznzne')], default='X', max_length=1),
        ),
    ]
