# Generated by Django 3.0.2 on 2020-01-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0002_auto_20200125_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='sex',
            field=models.CharField(choices=[('M', 'Pies'), ('F', 'Suczka'), ('X', 'Nieznzne')], default='X', max_length=1),
        ),
        migrations.AlterField(
            model_name='dog',
            name='race',
            field=models.CharField(max_length=128),
        ),
    ]
