# Generated by Django 3.0.2 on 2020-01-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0003_auto_20200125_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='sex',
            field=models.CharField(choices=[('M', 'Pies'), ('F', 'Suczka'), ('X', 'Nieznane')], default='X', max_length=1),
        ),
    ]
